main_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:showMainPage}
admin_page:
    path:     /admin/{value}
    defaults: { _controller: AppBundle:AdminPage:showAdminPage, value:'main'}